---
abstract: 'a prove plugin to keep output TAP reusable'
author:
  - 'Steffen Schwigon, C<< <ss5 at renormalist.net> >>'
  - 'Steffen Schwigon <ss5@renormalist.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Prove-Plugin-Idempotent
no_index:
  directory:
    - inc
    - t
requires:
  TAP::Parser: 3.24
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=App-Prove-Plugin-Idempotent
  license: http://dev.perl.org/licenses/
  repository: git://github.com/renormalist/App-Prove-Plugin-Idempotent.git
version: 0.01
